package net.minestom.server;

import net.minestom.server.utils.MajorMinorVersion;

/**
 * Minecraft protocol and data version constants.
 * <br>
 * Code autogenerated, do not edit!
 */
public final class MinecraftConstants {
    public static final String VERSION_NAME = "26.2";

    public static final int PROTOCOL_VERSION = 776;

    public static final int DATA_VERSION = 4903;

    public static final MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(88, 0);

    public static final MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(107, 1);

    private MinecraftConstants() {
    }
}
